apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.10.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: data
    count: 1
    config:
      node.name: quickstart-es-data-0
      cluster.initial_master_nodes: ["quickstart-es-data-0"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
        - name: elasticsearch-data
          emptyDir: {}

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: haystack
  name: haystack
spec:
  containers:
  - image: sanjaykumarkkr/haystack:1.0.21
    name: haystack
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
